# Generated by Django 4.0.2 on 2022-03-30 13:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zanr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(help_text='Zadejte název žánru', max_length=20, verbose_name='Název žánru')),
            ],
            options={
                'verbose_name': 'Žánr',
                'verbose_name_plural': 'Žánry',
                'ordering': ['nazev'],
            },
        ),
        migrations.CreateModel(
            name='Kniha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titul', models.CharField(error_messages={'blank': 'Titul knihy musí být vyplněn'}, help_text='Zadejte titul knihy', max_length=100, verbose_name='Titul knihy')),
                ('obsah', models.TextField(blank=True, help_text='Vložte obsah knihy', verbose_name='Obsah knihy')),
                ('pocet_stran', models.PositiveIntegerField(blank=True, help_text='Zadejte počet stran (max. 9999)', validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Počet stran')),
                ('rok_vydani', models.PositiveIntegerField(blank=True, help_text='Zadejte rok vydání (1500 - 2100)', validators=[django.core.validators.MinValueValidator(1500), django.core.validators.MaxValueValidator(2100)], verbose_name='Rok vydání')),
                ('obalka', models.ImageField(upload_to='obalky', verbose_name='Obálka knihy')),
                ('zanry', models.ManyToManyField(to='knihovna.Zanr')),
            ],
            options={
                'verbose_name': 'Kniha',
                'verbose_name_plural': 'Knihy',
                'ordering': ['titul'],
            },
        ),
    ]
