# Generated by Django 4.0.2 on 2022-03-30 14:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knihovna', '0003_alter_autor_narozeni_alter_autor_umrti'),
    ]

    operations = [
        migrations.AddField(
            model_name='kniha',
            name='vydavatelstvi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='knihovna.vydavatelstvi', verbose_name='Vydavatelství'),
        ),
        migrations.AlterField(
            model_name='kniha',
            name='pocet_stran',
            field=models.PositiveIntegerField(blank=True, help_text='Zadejte počet stran (max. 9999)', null=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Počet stran'),
        ),
        migrations.AlterField(
            model_name='kniha',
            name='rok_vydani',
            field=models.PositiveIntegerField(blank=True, help_text='Zadejte rok vydání (1500 - 2100)', null=True, validators=[django.core.validators.MinValueValidator(1500), django.core.validators.MaxValueValidator(2100)], verbose_name='Rok vydání'),
        ),
        migrations.AlterField(
            model_name='vydavatelstvi',
            name='adresa',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Adresa'),
        ),
    ]
