# Generated by Django 4.2 on 2023-04-23 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('knihovna', '0004_kniha_vydavatelstvi_alter_kniha_pocet_stran_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recenze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Vložte text recenze', verbose_name='Text recenze')),
                ('upraveno', models.DateTimeField(auto_now=True, help_text='Vložte text recenze', verbose_name='Text recenze')),
                ('hodnoceni', models.IntegerField(choices=[(0, ''), (1, '*'), (2, '**'), (3, '***'), (4, '****'), (5, '*****')], default=3)),
                ('kniha', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='knihovna.kniha')),
                ('recenzent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recenze',
                'verbose_name_plural': 'Recenze',
                'ordering': ['-hodnoceni'],
            },
        ),
    ]
